version: '2'
services: 
  airflow: 
    environment: 
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_USERNAME=user
      - AIRFLOW_PASSWORD=password
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
    image: "bitnami/airflow:1"
    ports: 
      - "8080:8080"
    volumes: 
      - "./data:/opt/bitnami/dataset"
      - "./src/script:/opt/bitnami/script"
      - "./src/airflow/dags:/opt/bitnami/airflow/dags"
      - "./src/airflow/plugins:/opt/bitnami/airflow/plugins"
  airflow-scheduler: 
    environment: 
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_LOAD_EXAMPLES=no
    image: "bitnami/airflow-scheduler:latest"
    volumes: 
      - "./data:/opt/bitnami/dataset"
      - "./src/script:/opt/bitnami/script"
      - "airflow_scheduler_data:/bitnami"
      - "./src/airflow/dags:/opt/bitnami/airflow/dags"
      - "./src/airflow/plugins:/opt/bitnami/airflow/plugins"
  airflow-worker: 
    environment: 
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=no
    image: "bitnami/airflow-worker:latest"
    volumes: 
      - "./data:/opt/bitnami/dataset"
      - "./src/script:/opt/bitnami/script"
      - "airflow_worker_data:/bitnami"
      - "./src/airflow/dags:/opt/bitnami/airflow/dags"
      - "./src/airflow/plugins:/opt/bitnami/airflow/plugins"
  postgresql: 
    environment: 
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=yes
    image: "bitnami/postgresql:latest"
    volumes: 
      - "postgresql_data:/bitnami/postgresql"
  redis: 
    environment: 
      - ALLOW_EMPTY_PASSWORD=yes
    image: "bitnami/redis:latest"
    volumes: 
      - "redis_data:/bitnami"
volumes: 
  airflow_data: 
    driver: local
  airflow_scheduler_data: 
    driver: local
  airflow_worker_data: 
    driver: local
  postgresql_data: 
    driver: local
  redis_data: 
    driver: local